### ISSUE TITLE
"enabledLiveAutoComplete": false has no effect

### ISSUE THREAD

**Issue by betafcc** [sqlectron/sqlectron-gui#643]
I'm using 1.36.0, macos, MySql 8 database (but I noticed on others as well).

I'm trying to disable the live completion but it just won't go
I tried both using the settings on the gui and editing sqlelectron.json, neither `"enabledLiveAutoComplete": false` nor ` "enabledAutoComplete": false` makes any effect, when I go to my database and start typing in the query editor, immediately it starts appearing.

It is quite annoying specially because I can't unset the 'enter commit completion', making it quite unpleasant to type anything before a newline.

Here is the full config file:

```json
{
  "servers": [
    {
      "id": "cb508927-9f47-41b7-b457-150425a2045a",
      "name": "mysql",
      "client": "mysql",
      "ssl": false,
      "host": "localhost",
      "port": 3306,
      "socketPath": null,
      "user": "root",
      "password": {
        "ivText": "6lv2/JcFt9rMLiANclLr0A==",
        "encryptedText": "GIYgFDGkmI0ZuYBBdK8Prg=="
      },
      "schema": null,
      "encrypted": true
    }
  ],
  "zoomFactor": 1,
  "limitQueryDefaultSelectTop": 100,
  "enabledDarkTheme": false,
  "disabledOpenAnimation": true,
  "csvDelimiter": ",",
  "connectionsAsList": false,
  "customFont": "Lato",
  "enabledAutoComplete": false,
  "enabledLiveAutoComplete": false
}
```

And the docker-compose file I'm using to run the db (although I doubt it makes any difference):

```
version: '3.3'
services:
  db:
    image: mysql:8
    command:
      - '--local-infile=1'
      - '--secure-file-priv='
    restart: always
    security_opt:
      - seccomp:unconfined
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./my-db:/var/lib/mysql
      - ./mysql-files:/var/lib/mysql-files
volumes:
  my-db:
  data:
```

Thanks for the otherwise awesome project!
